default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: <%= ENV['PG_PASSWORD'] || 'goodcars' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: login_form_development

test:
  <<: *default
  database: login_form_test

production:
  primary: &primary_production
    <<: *default
    database: login_form_production
    username: postgres
    password: <%= ENV['PG_PASSWORD'] || 'goodcars' %>
  cache:
    <<: *primary_production
    database: login_form_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: login_form_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: login_form_production_cable
    migrations_paths: db/cable_migrate
